version: '2'

services:
  nginx:
    image: nginx
    container_name: "web-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "web-php"
    volumes:
      - ./src:/src

  mysql:
    image: mysql
    container_name: "web-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 13306:3306

  postgres:
    restart: always
    image: postgres:alpine
    container_name: "web-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "web-redis"
    ports: 
      - 16379:6379
